// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecaxapflzhggokajlhbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjYXhhcGZsemhnZ29rYWpsaGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTQ1NDQsImV4cCI6MjA2MDY5MDU0NH0.fbI9afo2YcC0Z3zehNTZCp8yfuh3RtAU8J2dgj2K8oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);